#pragma once

#ifndef PYPILOT_CXX_DEFAULT_PORT
#define PYPILOT_CXX_DEFAULT_PORT 23322
#endif

#ifndef PYPILOT_CXX_NMEA_PORT
#define PYPILOT_CXX_NMEA_PORT 20220
#endif

#ifndef PYPILOT_CXX_CONTROL_PERIOD_US
#define PYPILOT_CXX_CONTROL_PERIOD_US 10000ULL
#endif

#ifndef PYPILOT_CXX_MAX_LINE
#define PYPILOT_CXX_MAX_LINE 256
#endif
